#!/bin/bash
while true; do
  ( echo -e 'HTTP/1.1 200 OK\r\n';
  well=$(curl -s -A brexit_exporter https://hasbritainlefttheeu.com | grep 'div class="well-have' -A 1 | grep -oi 'yes\|no')
  if [ -z "$(echo $well | grep -i yes)" ]; then
    well=1
  else
    well=0
  fi
  echo -e "# HELP britain_still_in_the_eu Is Britain still in the EU"
  echo -e "# TYPE britain_still_in_the_eu gauge"
  echo -e "britain_still_in_the_eu $well"
  ) | nc -lp 29319
done
